// 界面文字：中文。{n} 之类是占位符。
export const zh = {
  'app.name': '架构多巴胺',
  'app.tagline': '系统设计闯关 · 答得越对越热闹',
  'app.loadFail': '题库加载失败，请检查网络后刷新。',
  'common.ok': '好的', 'common.close': '关闭', 'common.cancel': '取消', 'common.back': '返回',
  'chapter.n': '第 {n} 章',

  'nav.label': '主菜单', 'nav.tree': '技能树', 'nav.trophies': '成就', 'nav.collection': '收藏', 'nav.calendar': '日历', 'nav.settings': '设置',

  'title.help': '玩法说明', 'title.streak': '{n} 天', 'title.mylevel': '我的水平',
  'title.placementSub': '先做一次实力检测，从合适的地方开始', 'title.allDone': '全部课程已掌握，来复习和挑战吧',
  'title.nextUp': '下一课：{name}', 'title.review': '复习错题（{n}）', 'title.rusty': '有 {n} 门课生锈了：做对一题就能擦亮。',
  'title.quests': '今日任务', 'title.questsHint': '全部完成送一把补签锤', 'title.byChapter': '按章节练习',
  'title.footer': '全部记录只保存在这台设备的浏览器里。', 'title.reader': '回到在线阅读版',
  'greet.first': '我是节点君！每答对一格，我们的机房就更热闹一点。',
  'greet.streak': '连续 {n} 天了，今天也别断！', 'greet.review': '错题攒了一些，复习一下吧？',
  'greet.back': '好久不见！先从“我的水平”热热身。', 'greet.growth': '这周比上周有进步，继续保持！',
  'greet.default0': '答错也没关系，不扣分、不结束。', 'greet.default1': '先答对一格，剩下的交给多巴胺。', 'greet.default2': '读懂比选对更重要，解析别跳过。',

  'login.title': '今日登录贴纸', 'login.body': '连续登录第 {n} 天，贴纸 +1', 'login.crown': '集齐一周，获得王冠！',
  'hammer.title': '用补签锤保住连续记录？', 'hammer.body': '中间空了 {n} 天，用 {n} 把补签锤补上，连续记录就不会断（现有 {have} 把）。',
  'hammer.use': '用补签锤', 'hammer.no': '不用了', 'hammer.done': '已补签，连续记录保住了',
  'rewards.title': '新的收获', 'rewards.trophies': '新成就', 'rewards.items': '新收藏', 'rewards.more': '还有 {n} 个新成就，去成就页查看。',

  'guide.skip': '跳过', 'guide.back': '上一步', 'guide.next': '下一步', 'guide.go': '开始！',
  'guide.intro.title': '欢迎来到架构多巴胺', 'guide.intro.body': '这是一套把系统设计面试笔记做成的闯关游戏。每答对一格，画面和音乐就多叠一层，答错也不扣分、不结束。',
  'guide.play.title': '节点君陪你玩', 'guide.play.body': '答题时它会跟着你的状态变化。连击越多、多巴值越高，装扮越夸张。',
  'guide.mylevel.title': '“我的水平”', 'guide.mylevel.body': '第一次先做一次实力检测，系统会判断你已经会哪些，之后自动安排新课和复习。',
  'guide.chapters.title': '按章节练习', 'guide.chapters.body': '想练哪一章就点哪一章，可以先看本章要点、课程列表和对应的阅读原文。',
  'guide.tree.title': '技能树、成就、收藏', 'guide.tree.body': '每一课都有掌握状态和 ★ 星级；玩得越多，解锁的音乐、皮肤和成就越多。',
  'guide.daily.title': '每日任务与连续记录', 'guide.daily.body': '每天 3 个小任务，全部完成送补签锤，漏一天也能补回连续记录。',
  'guide.start.title': '准备好了吗', 'guide.start.body': '点“我的水平”开始。右上角的“？”可以随时重看这份说明。',

  'play.mute': '静音', 'play.quit': '退出', 'play.demo': '自动演示', 'play.placement': '实力检测', 'play.review': '复习错题',
  'play.dopa': '多巴', 'play.combo': '连击 ×{n}', 'play.comboMax': '多巴 ×2 MAX', 'play.comboLost': '{n} 连击结束了',
  'play.extra': '加试', 'play.extraN': '加试 第 {n} 题', 'play.score': '{n} 分', 'play.finishExtra': '结算',
  'play.capsule': '回访题', 'play.multiHint': '选出全部 {n} 个正确项', 'play.orderHint': '按正确顺序依次点击', 'play.dopaMilestone': '多巴值突破 {v}！',
  'play.firstTry': '一次就对！', 'play.almost': '差一点，答对了（点错 {n} 次）', 'play.plus': '+{n} 分',
  'play.source': '查看原文', 'play.next': '下一题', 'play.toResult': '看结果',
  'play.questDone': '任务完成：{q}',
  'play.quitTitle': '退出本次游玩？', 'play.quitBody': '没做完的这一轮不会写入历史，但已经答过的题会保留。', 'play.quitOk': '退出',
  'judge.true': '正确', 'judge.false': '错误',
  'type.single': '单选', 'type.multi': '多选', 'type.judge': '判断', 'type.fill': '填空', 'type.order': '排序', 'type.match': '配对',
  'mode.self': '我的水平', 'mode.chapter': '章节', 'mode.practice': '练习', 'mode.review': '复习',

  'result.basicDone': '基本问题完成！', 'result.placementDone': '实力检测完成！', 'result.finalTitle': '本次结算', 'result.points': '分',
  'result.time': '用时 / 目标', 'result.firstTry': '一次答对', 'result.almost': '差一点', 'result.maxCombo': '最高连击', 'result.dopa': '多巴值', 'result.extraQ': '加试题数',
  'result.mastered': '掌握了「{name}」', 'result.star': '「{name}」升到 ★{n}', 'result.polished': '擦亮了「{name}」', 'result.placed': '检测判定你已掌握 {n} 门课',
  'result.growth': '比以前更好', 'result.questDone': '任务完成：{q}', 'result.hammer': '今日任务全部完成：补签锤 +1！', 'result.hammerFull': '今日任务全部完成！（补签锤已满）',
  'result.extra': '挑战加试', 'result.extraSub': '题目不限数，每题 10+5k 分', 'result.extraLocked': '一次答对率达到 {rate}% 才能加试（本次 {now}%）',
  'result.again': '再来一次', 'result.home': '回首页',
  'growth.ftRate': '一次答对率 {prev}% → {now}%', 'growth.time': '用时 {prev} 秒 → {now} 秒', 'growth.speed': '每题 {prev} 秒 → {now} 秒', 'growth.combo': '最高连击 {prev} → {now}', 'growth.score': '得分 {prev} → {now}', 'growth.answered': '解答题数 {prev} → {now}',

  'quest.play1': '完整玩完 1 次', 'quest.play2': '完整玩完 2 次', 'quest.combo5': '打出 5 连击', 'quest.combo20': '打出 20 连击', 'quest.ft5': '一次答对 5 题',
  'quest.review1': '复习 1 道错题', 'quest.new1': '做 1 道新课程的题', 'quest.extra1': '进入加试', 'quest.extra5': '加试里答 5 题', 'quest.chapter1': '按章节玩完 1 次',
  'quest.learn10': '在学习中的课程里答 10 题', 'quest.skill3': '「{lesson}」一次答对 3 题', 'quest.polish3': '擦亮「{lesson}」：一次答对 3 题',

  'tree.stars': '{n} 星', 'tree.mastered': '已掌握 {n} / {total} 课', 'tree.rust': '生锈：21 天没答对，做对一题即可擦亮', 'tree.rustShort': '生锈',
  'tree.s.new': '新课', 'tree.s.practice': '练习中', 'tree.s.mastered': '已掌握', 'tree.s.locked': '未解锁',
  'sheet.lessons': '课程', 'sheet.detail': '详情', 'sheet.labs': '相关交互实验', 'sheet.read': '阅读本章原文', 'sheet.playChapter': '练习本章',
  'sheet.practice': '练习这一课', 'sheet.lockedHint': '先掌握这些前提课程才能解锁（也可以直接在“按章节”里练）：',
  'sheet.recent': '最近 {n} 题里一次答对 {ft} 题', 'sheet.solved': '累计作答 {n} 次', 'sheet.fastest': '最快一次答对用时 {s}',
  'sheet.noRecord': '还没有这一课的记录。', 'sheet.masteryRule': '掌握条件：至少答过 6 题，最近 6 题里一次答对 5 题。',
  'sheet.nextStar': '下一颗 ★{n}：', 'sheet.allStars': '五颗星已集齐！',
  'sheet.star2': '最近 20 题一次答对率 ≥ 90%。', 'sheet.star3': '最近 10 题里一次答对 ≥ 5 题，且速度不慢于基准。',
  'sheet.star4': '在 ★3 之后至少隔 {days} 天，再连续 3 题一次答对。', 'sheet.star5': '最近 20 题一次答对率 ≥ 95%，且速度达到基准的 60% 以内。',
  'sheet.reset': '清除这一课的记录', 'sheet.resetBody': '会同时清掉依赖它的 {n} 门后续课程的记录和星级。历史、成就和收藏不受影响。', 'sheet.resetDone': '已清除',

  'trcat.all': '全部', 'trcat.keep': '坚持', 'trcat.volume': '数量', 'trcat.skill': '技能', 'trcat.extra': '加试', 'trcat.combo': '连击', 'trcat.accuracy': '精准',
  'trcat.dopa': '多巴', 'trcat.review': '复习', 'trcat.chapter': '章节', 'trcat.collection': '收藏', 'trcat.secret': '隐藏',
  'trf.all': '全部', 'trf.got': '已获得', 'trf.todo': '未获得',
  'tr.soon': '快要获得', 'tr.total': '已获得 {n} / {total}', 'tr.empty': '这里还没有成就。', 'tr.secretName': '？？？（隐藏成就）',
  'tr.streak': '连续 {n} 天游玩', 'tr.playDays': '累计游玩 {n} 天', 'tr.login': '登录贴纸 {n} 张', 'tr.crowns': '集齐 {n} 顶王冠', 'tr.quests': '每日任务全部完成 {n} 天',
  'tr.questDone': '完成 {n} 个任务', 'tr.hammers': '使用补签锤 {n} 次', 'tr.answered': '解答 {n} 道题', 'tr.cells': '答对 {n} 个输入', 'tr.plays': '完成 {n} 次基本问题',
  'tr.minutes': '累计游玩 {n} 分钟', 'tr.reads': '点开原文或实验 {n} 次', 'tr.mastered': '掌握 {n} 门课', 'tr.stars': '累计 {n} 颗星', 'tr.cleared': '通关 {n} 章',
  'tr.extraQ': '加试累计 {n} 题', 'tr.maxExtraQ': '一次加试答 {n} 题', 'tr.bestScore': '单次得分 {n}', 'tr.bestCombo': '最高 {n} 连击', 'tr.perfect': '{n} 次全部一次答对',
  'tr.ftRate': '一次答对率达到 {n}%（至少 100 题）', 'tr.type_single': '解答 {n} 道单选题', 'tr.type_multi': '解答 {n} 道多选题', 'tr.type_judge': '解答 {n} 道判断题',
  'tr.type_fill': '解答 {n} 道填空题', 'tr.type_order': '解答 {n} 道排序题', 'tr.type_match': '解答 {n} 道配对题', 'tr.dopa': '多巴值达到 10 的 {n} 次方',
  'tr.reviewSolved': '复习本里一次答对 {n} 题', 'tr.polished': '擦亮 {n} 次生锈课程', 'tr.unlocked': '解锁 {n} 个收藏',
  'tr.chPlay': '玩过第 {n} 章', 'tr.chClear': '通关第 {n} 章',
  'tr.secret.newYear': '元旦也在学', 'tr.secret.comeback': '隔了 7 天以上又回来', 'tr.secret.allModes': '四种模式都玩过', 'tr.secret.lateNight': '凌晨 0–5 点还在学',
  'tr.secret.perfect14': '14 题全部一次答对', 'tr.secret.perfectExtra5': '加试连答 5 题全对', 'tr.secret.oops100': '累计“差一点” 100 次', 'tr.secret.fast': '10 题全对且 90 秒内', 'tr.secret.dopaMax': '多巴值达到 10 的 8 次方',

  'col.intro': '玩得越多，解锁越多。每一类可以固定一个，也可以交给“随机”。', 'col.cat.music': '音乐', 'col.cat.skin': '节点君皮肤', 'col.cat.theme': '界面配色',
  'col.auto': '随机', 'col.autoHint': '从已解锁的里选', 'col.preview': '试听', 'col.set': '已设为：{name}',
  'col.music.chip': '电子 8-bit', 'col.music.lofi': 'Lo-fi 小夜曲', 'col.music.wa': '和风五声', 'col.music.rock': '摇滚冲刺',
  'col.skin.default': '节点蓝', 'col.skin.sakura': '樱花粉', 'col.skin.matcha': '抹茶绿', 'col.skin.sunset': '日落橙', 'col.skin.violet': '紫罗兰', 'col.skin.gold': '黄金',
  'col.theme.night': '夜航', 'col.theme.sakura': '樱花', 'col.theme.forest': '森林', 'col.theme.sunset': '日落', 'col.theme.ink': '水墨',
  'col.cond.plays': '完成 {n} 次基本问题', 'col.cond.playDays': '游玩 {n} 天', 'col.cond.dopa': '多巴值达到 10 的 {n} 次方', 'col.cond.cleared': '通关 {n} 章',
  'col.cond.bestCombo': '最高 {n} 连击', 'col.cond.mastered': '掌握 {n} 门课', 'col.cond.trophies': '获得 {n} 个成就', 'col.cond.answered': '解答 {n} 题',
  'col.cond.extraQ': '加试 {n} 题', 'col.cond.streak': '连续 {n} 天',

  'cal.prev': '上个月', 'cal.next': '下个月', 'cal.weekdays': '日,一,二,三,四,五,六', 'cal.streak': '连续', 'cal.longest': '最长', 'cal.playDays': '游玩天数', 'cal.hammers': '补签锤',
  'cal.hammerHelp': '补签锤：漏玩的日子可以补上，保住连续记录（初始 1 把，最多 3 把；完成每日任务可再得）。',
  'cal.login': '累计登录贴纸 {n} 张，王冠 {c} 顶', 'cal.nocount': '这一天用补签锤补上了', 'cal.nothing': '这一天没有记录。', 'cal.sealDay': '当天贴纸：{s}',
  'cal.playLine': '{mode} · 一次答对 {ft}/{n} · 加试 {extra} 题 · 最高连击 {combo}',

  'set.lang': '语言 / Language', 'set.count': '每次题数', 'set.countHint': '基本问题的题数，完成即得 100 分。', 'set.sound': '声音', 'set.on': '开', 'set.off': '关', 'set.volume': '音量',
  'set.motion': '动效强度', 'set.motionHint': '光敏或容易眩晕时请调低。', 'set.motion0': '关闭', 'set.motion1': '弱', 'set.motion2': '标准',
  'set.pace': '连击计时', 'set.paceHint': '计时只会让连击断掉，不扣分。需要慢慢读题可放宽或关闭。', 'set.pace.normal': '标准', 'set.pace.relaxed': '宽松', 'set.pace.off': '关闭',
  'set.autoNext': '一次答对后自动下一题', 'set.autoNextHint': '想认真看解析时保持关闭。',
  'set.demo': '自动演示', 'set.demoHint': '看节点君自己打一轮，演示不会写入你的记录。', 'set.demoBtn': '开始演示',
  'set.backup': '备份', 'set.backupHint': '导出或导入全部记录（JSON 文件），换设备时使用。', 'set.export': '导出', 'set.import': '导入', 'set.importBody': '导入会覆盖这台设备上的全部记录。', 'set.importDone': '已导入', 'set.importFail': '文件格式不对，没有导入',
  'set.reset': '清空全部记录', 'set.resetHint': '不可恢复，建议先导出备份。', 'set.resetBody': '会删除全部进度、成就和收藏，且无法恢复。', 'set.resetDone': '已清空',
  'about.title': '关于', 'about.body': '题目来自《系统设计面试》中文学习版的练习题库，共 1039 题，每题都对照正文校对过。',
  'about.credit': '玩法框架参考', 'about.privacy': '所有记录只保存在你的浏览器里，不上传。',
};
