// UI strings: English. {n} etc. are placeholders.
export const en = {
  'app.name': 'Arch Rush',
  'app.tagline': 'System design, gamified · the more you get right, the wilder it gets',
  'app.loadFail': 'Could not load the question bank. Check your connection and reload.',
  'common.ok': 'OK', 'common.close': 'Close', 'common.cancel': 'Cancel', 'common.back': 'Back',
  'chapter.n': 'Ch. {n}',

  'nav.label': 'Main menu', 'nav.tree': 'Skill tree', 'nav.trophies': 'Trophies', 'nav.collection': 'Collection', 'nav.calendar': 'Calendar', 'nav.settings': 'Settings',

  'title.help': 'How to play', 'title.streak': '{n} d', 'title.mylevel': 'My level',
  'title.placementSub': 'Take a quick placement check to start at the right spot', 'title.allDone': 'Every lesson mastered. Review and challenge yourself.',
  'title.nextUp': 'Next: {name}', 'title.review': 'Review mistakes ({n})', 'title.rusty': '{n} lesson(s) went rusty: get one right to polish them.',
  'title.quests': "Today's quests", 'title.questsHint': 'Finish all three for a streak hammer', 'title.byChapter': 'Practice by chapter',
  'title.footer': 'All progress is stored only in this browser on this device.', 'title.reader': 'Back to the reading edition',
  'greet.first': "I'm Nodey! Every cell you get right makes our server room livelier.",
  'greet.streak': '{n} days in a row. Keep it going today!', 'greet.review': 'Your mistakes are piling up. Review a few?',
  'greet.back': 'Long time no see! Warm up with "My level".', 'greet.growth': "You're ahead of last week. Keep it up!",
  'greet.default0': "Wrong answers cost nothing. No game over.", 'greet.default1': 'Get one cell right and let the dopamine do the rest.', 'greet.default2': 'Understanding beats guessing. Read the explanations.',

  'login.title': "Today's login sticker", 'login.body': 'Day {n} of your login streak: +1 sticker', 'login.crown': 'A full week. You earned a crown!',
  'hammer.title': 'Use a hammer to keep your streak?', 'hammer.body': 'You skipped {n} day(s). Use {n} hammer(s) to cover them and the streak survives (you have {have}).',
  'hammer.use': 'Use hammer', 'hammer.no': 'No thanks', 'hammer.done': 'Covered. Your streak is safe.',
  'rewards.title': 'New rewards', 'rewards.trophies': 'New trophies', 'rewards.items': 'New collection items', 'rewards.more': '{n} more trophies. See the Trophies page.',

  'guide.skip': 'Skip', 'guide.back': 'Back', 'guide.next': 'Next', 'guide.go': 'Start!',
  'guide.intro.title': 'Welcome to Arch Rush', 'guide.intro.body': 'A game built from system design interview notes. Every correct cell adds another layer of visuals and music. Mistakes cost nothing and never end the run.',
  'guide.play.title': 'Nodey plays along', 'guide.play.body': 'It reacts as you play. The bigger your combo and dopa value, the wilder its outfit.',
  'guide.mylevel.title': '"My level"', 'guide.mylevel.body': 'Start with a placement check. It works out what you already know, then schedules new lessons and reviews for you.',
  'guide.chapters.title': 'Practice by chapter', 'guide.chapters.body': 'Tap any chapter to see its key points, lessons and the matching reading material.',
  'guide.tree.title': 'Skill tree, trophies, collection', 'guide.tree.body': 'Each lesson has a mastery state and a star rank. Play more to unlock music, skins and trophies.',
  'guide.daily.title': 'Daily quests and streaks', 'guide.daily.body': 'Three small quests a day. Finish them all for a streak hammer that can cover a missed day.',
  'guide.start.title': 'Ready?', 'guide.start.body': 'Tap "My level" to begin. The "?" at the top right replays this guide.',

  'play.mute': 'Mute', 'play.quit': 'Quit', 'play.demo': 'Auto demo', 'play.placement': 'Placement check', 'play.review': 'Review mistakes',
  'play.dopa': 'DOPA', 'play.combo': 'Combo ×{n}', 'play.comboMax': 'Dopa ×2 MAX', 'play.comboLost': '{n} combo ended',
  'play.extra': 'Extra', 'play.extraN': 'Extra · Q{n}', 'play.score': '{n} pts', 'play.finishExtra': 'Finish',
  'play.capsule': 'Revisit', 'play.multiHint': 'Pick all {n} correct options', 'play.orderHint': 'Tap the items in the right order', 'play.dopaMilestone': 'Dopa passed {v}!',
  'play.firstTry': 'First try!', 'play.almost': 'Close! Got it ({n} slip-ups)', 'play.plus': '+{n} pts',
  'play.source': 'Read the source', 'play.next': 'Next', 'play.toResult': 'See results',
  'play.questDone': 'Quest complete: {q}',
  'play.quitTitle': 'Quit this run?', 'play.quitBody': 'The unfinished round will not be saved to history, but answered questions are kept.', 'play.quitOk': 'Quit',
  'judge.true': 'True', 'judge.false': 'False',
  'type.single': 'Single choice', 'type.multi': 'Multi choice', 'type.judge': 'True / False', 'type.fill': 'Fill in', 'type.order': 'Ordering', 'type.match': 'Matching',
  'mode.self': 'My level', 'mode.chapter': 'Chapter', 'mode.practice': 'Practice', 'mode.review': 'Review',

  'result.basicDone': 'Base round complete!', 'result.placementDone': 'Placement check complete!', 'result.finalTitle': 'Final result', 'result.points': 'pts',
  'result.time': 'Time / target', 'result.firstTry': 'First try', 'result.almost': 'Slip-ups', 'result.maxCombo': 'Best combo', 'result.dopa': 'Dopa', 'result.extraQ': 'Extra Qs',
  'result.mastered': 'Mastered "{name}"', 'result.star': '"{name}" reached ★{n}', 'result.polished': 'Polished "{name}"', 'result.placed': 'The check places you as having mastered {n} lessons',
  'result.growth': 'Better than before', 'result.questDone': 'Quest complete: {q}', 'result.hammer': 'All quests done: +1 streak hammer!', 'result.hammerFull': 'All quests done! (hammers are full)',
  'result.extra': 'Go for extra', 'result.extraSub': 'Unlimited questions, 10+5k pts each', 'result.extraLocked': 'You need {rate}% first-try to unlock extra (this round: {now}%)',
  'result.again': 'Play again', 'result.home': 'Home',
  'growth.ftRate': 'First-try rate {prev}% → {now}%', 'growth.time': 'Time {prev}s → {now}s', 'growth.speed': 'Per question {prev}s → {now}s', 'growth.combo': 'Best combo {prev} → {now}', 'growth.score': 'Score {prev} → {now}', 'growth.answered': 'Answered {prev} → {now}',

  'quest.play1': 'Finish 1 round', 'quest.play2': 'Finish 2 rounds', 'quest.combo5': 'Reach a 5 combo', 'quest.combo20': 'Reach a 20 combo', 'quest.ft5': 'Get 5 questions right first try',
  'quest.review1': 'Review 1 missed question', 'quest.new1': 'Answer 1 question from a new lesson', 'quest.extra1': 'Enter extra', 'quest.extra5': 'Answer 5 extra questions', 'quest.chapter1': 'Finish 1 chapter round',
  'quest.learn10': 'Answer 10 questions in lessons you are learning', 'quest.skill3': '3 first-try answers in "{lesson}"', 'quest.polish3': 'Polish "{lesson}": 3 first-try answers',

  'tree.stars': '{n} stars', 'tree.mastered': '{n} / {total} lessons mastered', 'tree.rust': 'Rusty: no first-try win in 21 days. One right answer polishes it.', 'tree.rustShort': 'rusty',
  'tree.s.new': 'New', 'tree.s.practice': 'In progress', 'tree.s.mastered': 'Mastered', 'tree.s.locked': 'Locked',
  'sheet.lessons': 'Lessons', 'sheet.detail': 'Details', 'sheet.labs': 'Related interactive labs', 'sheet.read': 'Read the chapter', 'sheet.playChapter': 'Practice chapter',
  'sheet.practice': 'Practice this lesson', 'sheet.lockedHint': 'Master these first to unlock it (or practice it directly under "by chapter"):',
  'sheet.recent': '{ft} of the last {n} answered first try', 'sheet.solved': '{n} answers in total', 'sheet.fastest': 'Fastest first-try answer: {s}',
  'sheet.noRecord': 'No record for this lesson yet.', 'sheet.masteryRule': 'To master: answer at least 6, with 5 of the last 6 first try.',
  'sheet.nextStar': 'Next ★{n}: ', 'sheet.allStars': 'All five stars collected!',
  'sheet.star2': '90%+ first-try over the last 20.', 'sheet.star3': 'At least 5 of the last 10 first try, at baseline speed or faster.',
  'sheet.star4': 'At least {days} days after ★3, then 3 first-try answers in a row.', 'sheet.star5': '95%+ first-try over the last 20, at 60% of baseline time or faster.',
  'sheet.reset': 'Clear this lesson', 'sheet.resetBody': 'This also clears the records and stars of the {n} later lessons that depend on it. History, trophies and collection stay.', 'sheet.resetDone': 'Cleared',

  'trcat.all': 'All', 'trcat.keep': 'Streaks', 'trcat.volume': 'Volume', 'trcat.skill': 'Skills', 'trcat.extra': 'Extra', 'trcat.combo': 'Combo', 'trcat.accuracy': 'Accuracy',
  'trcat.dopa': 'Dopa', 'trcat.review': 'Review', 'trcat.chapter': 'Chapters', 'trcat.collection': 'Collection', 'trcat.secret': 'Secret',
  'trf.all': 'All', 'trf.got': 'Earned', 'trf.todo': 'Not yet',
  'tr.soon': 'Almost there', 'tr.total': '{n} / {total} earned', 'tr.empty': 'No trophies here yet.', 'tr.secretName': '??? (secret)',
  'tr.streak': 'Play {n} days in a row', 'tr.playDays': 'Play on {n} days', 'tr.login': '{n} login stickers', 'tr.crowns': 'Collect {n} crowns', 'tr.quests': 'Finish all quests on {n} days',
  'tr.questDone': 'Complete {n} quests', 'tr.hammers': 'Use {n} streak hammers', 'tr.answered': 'Answer {n} questions', 'tr.cells': 'Get {n} cells right', 'tr.plays': 'Finish {n} base rounds',
  'tr.minutes': 'Play for {n} minutes', 'tr.reads': 'Open the source or a lab {n} times', 'tr.mastered': 'Master {n} lessons', 'tr.stars': 'Earn {n} stars', 'tr.cleared': 'Clear {n} chapters',
  'tr.extraQ': '{n} extra questions in total', 'tr.maxExtraQ': '{n} extra questions in one run', 'tr.bestScore': 'Score {n} in one run', 'tr.bestCombo': 'Reach a {n} combo', 'tr.perfect': '{n} rounds all first try',
  'tr.ftRate': 'Reach {n}% first-try (100+ questions)', 'tr.type_single': 'Answer {n} single-choice questions', 'tr.type_multi': 'Answer {n} multi-choice questions', 'tr.type_judge': 'Answer {n} true/false questions',
  'tr.type_fill': 'Answer {n} fill-in questions', 'tr.type_order': 'Answer {n} ordering questions', 'tr.type_match': 'Answer {n} matching questions', 'tr.dopa': 'Dopa reaches 10^{n}',
  'tr.reviewSolved': 'Solve {n} review questions first try', 'tr.polished': 'Polish rusty lessons {n} times', 'tr.unlocked': 'Unlock {n} collection items',
  'tr.chPlay': 'Play chapter {n}', 'tr.chClear': 'Clear chapter {n}',
  'tr.secret.newYear': 'Studying on New Year’s Day', 'tr.secret.comeback': 'Back after 7+ days away', 'tr.secret.allModes': 'Played all four modes', 'tr.secret.lateNight': 'Still learning at 0–5 am',
  'tr.secret.perfect14': '14 questions, all first try', 'tr.secret.perfectExtra5': '5 extra questions in a row, no slips', 'tr.secret.oops100': '100 slip-ups in total', 'tr.secret.fast': '10 perfect answers in 90 seconds', 'tr.secret.dopaMax': 'Dopa reaches 10^8',

  'col.intro': 'Play more to unlock more. Pick one per category, or leave it on random.', 'col.cat.music': 'Music', 'col.cat.skin': 'Nodey skins', 'col.cat.theme': 'Color themes',
  'col.auto': 'Random', 'col.autoHint': 'Picks from unlocked', 'col.preview': 'Preview', 'col.set': 'Set to: {name}',
  'col.music.chip': 'Chiptune 8-bit', 'col.music.lofi': 'Lo-fi night', 'col.music.wa': 'Japanese pentatonic', 'col.music.rock': 'Rock rush',
  'col.skin.default': 'Node blue', 'col.skin.sakura': 'Sakura pink', 'col.skin.matcha': 'Matcha green', 'col.skin.sunset': 'Sunset orange', 'col.skin.violet': 'Violet', 'col.skin.gold': 'Gold',
  'col.theme.night': 'Night flight', 'col.theme.sakura': 'Sakura', 'col.theme.forest': 'Forest', 'col.theme.sunset': 'Sunset', 'col.theme.ink': 'Ink',
  'col.cond.plays': 'Finish {n} base rounds', 'col.cond.playDays': 'Play on {n} days', 'col.cond.dopa': 'Dopa reaches 10^{n}', 'col.cond.cleared': 'Clear {n} chapters',
  'col.cond.bestCombo': 'Reach a {n} combo', 'col.cond.mastered': 'Master {n} lessons', 'col.cond.trophies': 'Earn {n} trophies', 'col.cond.answered': 'Answer {n} questions',
  'col.cond.extraQ': '{n} extra questions', 'col.cond.streak': '{n} days in a row',

  'cal.prev': 'Previous month', 'cal.next': 'Next month', 'cal.weekdays': 'Su,Mo,Tu,We,Th,Fr,Sa', 'cal.streak': 'Streak', 'cal.longest': 'Longest', 'cal.playDays': 'Days played', 'cal.hammers': 'Hammers',
  'cal.hammerHelp': 'Streak hammers cover days you missed (start with 1, hold up to 3; finishing all daily quests earns another).',
  'cal.login': '{n} login stickers, {c} crowns', 'cal.nocount': 'Covered with a streak hammer', 'cal.nothing': 'Nothing recorded on this day.', 'cal.sealDay': "That day's sticker: {s}",
  'cal.playLine': '{mode} · first try {ft}/{n} · extra {extra} · best combo {combo}',

  'set.lang': 'Language / 语言', 'set.count': 'Questions per round', 'set.countHint': 'Base round length. Finishing it scores 100.', 'set.sound': 'Sound', 'set.on': 'On', 'set.off': 'Off', 'set.volume': 'Volume',
  'set.motion': 'Motion', 'set.motionHint': 'Turn this down if flashing or movement bothers you.', 'set.motion0': 'Off', 'set.motion1': 'Low', 'set.motion2': 'Full',
  'set.pace': 'Combo timer', 'set.paceHint': 'The timer only breaks a combo, never costs points. Relax or disable it if you like to read slowly.', 'set.pace.normal': 'Normal', 'set.pace.relaxed': 'Relaxed', 'set.pace.off': 'Off',
  'set.autoNext': 'Auto-advance after a first-try answer', 'set.autoNextHint': 'Leave off if you want to read each explanation.',
  'set.demo': 'Auto demo', 'set.demoHint': 'Watch Nodey play a round. The demo never touches your progress.', 'set.demoBtn': 'Start demo',
  'set.backup': 'Backup', 'set.backupHint': 'Export or import all progress as a JSON file, e.g. to switch devices.', 'set.export': 'Export', 'set.import': 'Import', 'set.importBody': 'Importing replaces all progress on this device.', 'set.importDone': 'Imported', 'set.importFail': 'That file is not a valid backup. Nothing was imported.',
  'set.reset': 'Erase all progress', 'set.resetHint': 'Cannot be undone. Export a backup first.', 'set.resetBody': 'This deletes all progress, trophies and collection items. It cannot be undone.', 'set.resetDone': 'Erased',
  'about.title': 'About', 'about.body': 'Questions come from the practice bank of the Chinese-edition System Design Interview notes: 1,039 questions, each checked against the text.',
  'about.credit': 'Gameplay framework inspired by', 'about.privacy': 'All progress stays in your browser and is never uploaded.',
};
